### ISSUE TITLE
Project name: typo?

### ISSUE THREAD

**Issue by Hexstream** [ichimal/infix-dollar-reader#2]
Is there some deep reason this isn't called "infix-dollar-reader" instead?...

**Comment by ichimal** [comment]
Oh, I was wrong. I'm not native speaker, so I'v misunderstood the spelling.
I'll correct the project name.
Thank you.

**Comment by ichimal** [comment]
Done;
1. changed repository name.
2. changed file names.
3. changed any file contents.
close #2
